# Generated by Django 4.0.1 on 2022-01-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('ISO2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPermitInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_travel', models.DateTimeField(blank=True, null=True)),
                ('date_of_return', models.DateTimeField(blank=True, null=True)),
                ('age_of_traveler', models.IntegerField()),
                ('adult_present', models.BooleanField(blank=True, null=True)),
                ('inquiry_status', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_denial', models.TextField(blank=True, default='NONE', max_length=300, null=True)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_countries', to='covid_travel_inquiry_app.country')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_countries', to='covid_travel_inquiry_app.country')),
            ],
            options={
                'verbose_name_plural': 'Covid19 Travel Permit Inquiries',
                'db_table': 'travel_permit_inquiry',
            },
        ),
    ]
