# Generated by Django 4.0.1 on 2022-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_travel_inquiry_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryListUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Countries-List-Updates',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='travelpermitinquiry',
            options={'verbose_name_plural': 'Covid19 Travel Permit Inquiries'},
        ),
        migrations.RemoveField(
            model_name='travelpermitinquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='travelpermitinquiry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelpermitinquiry',
            name='adult_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelpermitinquiry',
            name='date_of_travel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelpermitinquiry',
            name='inquiry_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='travelpermitinquiry',
            name='reason_for_denial',
            field=models.TextField(blank=True, default='NONE', max_length=300, null=True),
        ),
    ]
