name: pbp_core CI/CD

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Collectstatic, makemigrations & migrate
      run: |
        
        python manage.py collectstatic

        python manage.py makemigrations

        python manage.py migrate

    - name: Run Tests
       run: |
         python manage.py test

        
  deploy:
    runs-on: self-hosted
    needs: build
    name: deploy


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create Vitrual_Env & Install Dependencies
      run: |

        mkdir -p ~/pbp_core
        cd ~/pbp_core

        #virtualenv myprojectenv
        source myprojectenv/bin/activate


        cd ~/actions-runner/deploy/pbp_core/pbp_core
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi



    - name: Create Migrations Backup Directories
      run: |  
        mkdir -p ~/pbp_core/migrations/covid_travel_inquiry_app/migrations


        cd ~/pbp_core/migrations
        tree


    - name: RSYNC Backup Migrations To Workin Directory
      run: |
        rsync -a --delete ~/pbp_core/migrations/covid_travel_inquiry_app/migrations ~/actions-runner/deploy/pbp_core/pbp_core/covid_travel_inquiry_app

        
    - name: COLLECTSTATIC
      run: |
        cd ~/actions-runner/deploy/pbp_core/pbp_core                
        python manage.py collectstatic

    - name: MAKEMIGRATIONS
      run: |
        cd ~/actions-runner/deploy/pbp_core/pbp_core 
        python manage.py makemigrations covid_travel_inquiry_app


    ## All
    - name: APP-MIGRATE
      run: |
        cd ~/actions-runner/deploy/pbp_core/pbp_core        
        python manage.py migrate

    ## covid_travel_inquiry_app
    - name: MIGRATE-covid_travel_inquiry_app
      run: |
        cd ~/actions-runner/deploy/pbp_core/pbp_core        
        python manage.py migrate covid_travel_inquiry_app

    - name: Rsync Workin Directory to Backup Migrations-covid_travel_inquiry_app
      run: |
        rsync -a --delete ~/actions-runner/deploy/pbp_core/pbp_core/covid_travel_inquiry_app/migrations ~/pbp_core/migrations/covid_travel_inquiry_app
        cd ~/pbp_core/migrations/covid_travel_inquiry_app
        tree



    - name: Backup Migrations_Updated
      run: |
        cd ~/pbp_core/migrations
        tree


